spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/task
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug
#  org.hibernate.type: trace