spring:
  datasource:
    url: jdbc:mysql://mbslaw-db.cszatmtp17tv.ap-northeast-2.rds.amazonaws.com:3306/byeon
    username: byeon
    password: M_5%Aw?A!Gbyeon
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
